#include<stdio.h>
#include<stdlib.h>
#definepi3.1415926
intmain()
{
constdoubleppi=pi;
doublevar;
printf("num:190210504\nexp_2\n");
printf("pleaseinputvar:");
scanf("%lf",&var);
doublevar=4.0/3.0;
var*=var*var*var*pi;
doublevar=4.0;
var*=pi*var*var;
printf("thevolumeofsphereis%lf\n",var);
printf("thesurfacevarofsphereis%lf\n",var);
return0;
}
