#include<stdio.h>
#include<math.h>
intmain()
{
printf("Number:190210504\n");
printf("calculate_triangle\n");
floatvar,var,var,var,var;
printf("Inputvar,var,var:");
scanf("%f,%f,%f",&var,&var,&var);
if((var+var)>var&&(var+var)>var&&(var+var)>var){
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%f\n",var);
}
else{
printf("theycouldnotcombinevartriangle\n");
}
return0;
}
