#include<stdio.h>
#include<stdlib.h>
#include<math.h>
intmain()
{
printf("number:190210508\n实验2.2\n");
doublevar,var,var;
doublevar;
printf("inputvarvarvar");
scanf("%lf,%lf,%lf",&var,&var,&var);
if((var+var>var)&&(var+var>var)&&(var+var>var))
{
var=(var+var+var)/2;
printf("area=%lf",(double)sqrt(var*(var-var)*(var-var)*(var-var)));
exit(0);
}
else
printf("不是三角形");
}
