#include<stdio.h>
#include<stdlib.h>
#include<math.h>
intmain()
{
floatvar,var,var;
floatvar;
floatvar;
printf("Number:180210129\n");
printf("Subject.2.program.2\n\n");
printf("请输入三角形的三个边长a,var,var:");
scanf("%f,%f,%f",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("这个三角形的面积是：%f",var);
}
else
{
printf("这三边无法构成一个三角形");
}
return0;
}
