#include<stdio.h>
#include<stdlib.h>
intmain()
{
printf("pleaseinputvar,var,var:");
floatvar,var;
floatvar,var,var;
scanf("%f%f%f",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("可以构成一个三角形\narea=%f\n",var);
}
else
{
printf("不可构成一个三角形");
}
}
