#include<stdio.h>
#include<math.h>
intmain()
{
floatvar,var,var,var,var;
printf("Number:190210507\n");
printf("subjectNo.2-programNo.2");
printf("Pleaseinputvarvarvar:");
scanf("%f%f%f",&var,&var,&var);
if((var+var>var)&&(var+var>var)&&(var+var>var))
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("area=%f",var);
}
else
printf("Error!");
}
