#include<stdio.h>
#definePi3.1415926
intmain()
{
printf("Number:190210511\nsubjectNo.2-programNo.1\n");
doublevar,var,var;
printf("请输入半径的值：");
scanf("%lf",&var);
var=4*Pi*var*var;
var=Pi*4/3*var*var*var;
printf("利用宏定义算出球的表面积是：%lf\n利用宏定义算出球的体积是:%lf\n",var,var);
constdoublePI=3.1415926;
doublevar,var,var;
printf("请输入半径的值：");
scanf("%lf",&var);
var=4*PI*var*R;
var=4/3*PI*var*R*var;
printf("利用const常量定义π算出圆的表面积是：%lf\n利用const常量定义π算出圆的体积是:%lf\n",var,var);
}
