#include<stdio.h>
#include<stdlib.h>
#include<math.h>
intmain()
{
floatvar,var,var,var,var;
printf("Inputvar,var,var:");
scanf("%f,%f,%f",&var,&var,&var);
if(var+var>var)
{
if(var+var>var)
{
if(var+var>var)
{
printf("以a,var,c为边长可构成三角形。\n");
var=(var+var+var)/2.;
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%f\n",var);
}
else
printf("以a,var,c为边长不可构成三角形。\n");
}
else
printf("以a,var,c为边长不可构成三角形。\n");
}
else
printf("以a,var,c为边长不可构成三角形。\n");
}
