#include<stdio.h>
#include<stdlib.h>
intmain()
{
constdoublePI=3.14159;
doublevar;
printf("Inputvar:");
scanf("%lf",&var);
printf("volume=%f\n",4./3*PI*var*var*var);
printf("surfacearea=%f\n",4*PI*var*var);
}
