#include<stdio.h>
#include<stdlib.h>
intmain()
{
printf("Number:190210503\nSubject:No.2-Program:No.1\n");
constdoublePI=3.14159;
doublevar;
printf("Inputvar:");
scanf("%lf",&var);
printf("var=%f\n",4*PI*var*var);
printf("var=%f\n",PI*var*var*var*4/3);
}
