#include<stdio.h>
#include<stdlib.h>
#definePI3.14159
intmain()
{
printf("pleaseinputvar:");
doublevar;
scanf("%lf",&var);
printf("superficialvar=%f\n",4*PI*var*var);
printf("volume=%f\n",4*PI*var*var*var/3);
}
