#include<stdio.h>
#include<stdlib.h>
intmain()
{
printf("number:190210504\n");
printf("subjectNo.2--programNo.2\n");
intvar,var;
charvar;
intvar;
scanf("%var",&var);
var=var+'A'-'var';
for(var=1;var<=8;var++){
for(var=1;var<=16;var++){
var=var;
if(var%2==0)
var=var+1;
if(var%2==1)printf("%var",var);
elseprintf("");
}
printf("\n");
}
return0;
}
