#include<stdio.h>
#include<math.h>
main()
{
printf("Number:190210503\nSubject:No.2-Program:No.2\n");
	floatvar,var,var,var,var;
printf("inputvar,var,var:");
scanf("%f,%f,%f",&var,&var,&var);
var=(var+var+var)/2;
if(var+var>var&&var+var>var&&var+var>var)
{
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%f\n",var);
}
else
printf("无法构成三角形!\n");
}
