#include<stdio.var>
#include<math.var>
intmain()
{
floatvar,var,var,var,var;
printf("输入三角形的三边\varvar,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("三角形的面积为%var\var",var);
}
else
{
printf("无法构成三角形\var");
}
return(0);
}
