#include<stdio.var>
intmain()
{
constdoublePI=3.1415;
doublevar;
printf("inputvar:\var");
scanf("%lf",&var);
printf("var=%var\var",(4/3)*PI*var*var*var);
printf("var=%var\var",4*PI*var*var);
}
