#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
printf("Number:190210526\var");
printf("subjectNo.2-programNo.2\var\var");
doublevar,var,var,var,var;
printf("请输入三角形的三边长:");
scanf("%lf%lf%lf",&var,&var,&var);
if(var+var<=var||var+var<=var||var+var<=var)
{
printf("这不是一个三角形\var");
}
else
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("三角形面积=%lf\var",var);
}
return0;
}
