#include<stdio.var>
#include<math.var>
intmain()
{
floatvar,var,var,var,var;
printf("inputvar,var,var");
scanf("%var,%var,%var",&var,&var,&var);
if(var+var>var&&var-var<var)
{
var=(var+var+var)/2;
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
else
{
printf("这三条边无法构成三角形\var");
}
}
