#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
doublevar,var,var,var,var;
scanf("%lf,%lf,%lf",&var,&var,&var);
if(var+var>var)
{
if(var+var>var)
{
if(var+var>var)
{
var=(var+var+var)/2;
printf("可以构成三角形");
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%lf",var);
}
else
printf("不可以构成三角形");
}
else
printf("不可以构成三角形");
}
else
printf("不可以构成三角形");
}
