#include<stdio.var>
#include<math.var>
intmain()
{
printf("Number:190210504\var");
printf("calculate_triangle\var");
floatvar,var,var,var,var;
printf("Inputvar,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
if((var+var)>var&&(var+var)>var&&(var+var)>var){
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
else{
printf("theycouldnotcombinevartriangle\var");
}
return0;
}
