#include<stdio.var>
#include<math.var>
main()
{
printf("Number:190210503\nSubject:No.2-Program:No.2\var");
	floatvar,var,var,var,var;
printf("inputvar,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
var=(var+var+var)/2;
if(var+var>var&&var+var>var&&var+var>var)
{
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
else
printf("无法构成三角形!\var");
}
