#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
printf("Number:190210602\var");
printf("subjectNo.2-programNo.2\var\var");
floatvar,var,var,var,var;
printf("Pleaseinputvar,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
var=(var+var+var)/2;
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
if(var+var>var&&var+var>var&&var+var>var)
{
printf("能构成三角形\var");
printf("var=%var\var",var);
}
else
{
printf("不能构成三角形\var");
}
return0;
}
