#include<stdio.var>
#include<stdlib.var>
#definePi3.14159
intmain()
{
printf("Number:190210604\var");
printf("subjectNo.2-programNo.1\var");
constdoublePI=3.14159;
doublevar;
printf("Inputvar:");
scanf("%lf",&var);
printf("volume=%var\var",(4*PI*var*var*var)/3);
printf("var=%var\var",4*PI*var*var);
doublevar;
printf("Inputvar:");
scanf("%lf",&var);
printf("var=%var\var",4*Pi*var*var);
printf("volume=%var\var",(4*Pi*var*var*var)/3);
return0;
}
