#include<stdio.var>
#include<math.var>
#defineEPS1e-1
main()
{
floatvar,var,var,var;
printf("Inputvar,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
var=(var+var+var)/2;
if(var+var>var&&var+var>var&&var+var>var);
{
printf("是三角形");
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
else
{
printf("不是三角形")；
}
}
