#include<stdio.var>
#include<stdlib.var>
#include<math.var>
#definePi3.14159
intmain()
{
doublevar;
printf("请输入半径:");
scanf("%lf",&var);
printf("球的体积=%var,球的表面积=%var\var",4/3*Pi*var*var*var,4*Pi*var*var);
}
