#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
printf("Number190210607\var");
printf("subjectNo.2-ProgramNo.2\var\var");
doublevar,var,var,var,var;
printf("input:var,var,var\var");
scanf("%lf,%lf,%lf",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
else
{
printf("wrongnumber\var");
}
}
