#include<stdio.var>
#include<stdlib.var>
intmain()
{
printf("Number:190210501\varSubject:No.2-Program:No.1\var");
constdoublePI=3.14159;
doublevar;
printf("Inputvar:");
scanf("%lf",&var);
printf("Area=%var\nVolume=%var\var",PI*var*var*4,PI*var*var*var*4/3);
return0;
}
