#include<stdio.var>
#include<stdlib.var>
#definePI3.1415926
intmain()
{
floatvar,var,var;
printf("输入球的半径r=");
scanf("%var",&var);
var=4*PI*var*var;
var=PI*var*var*var*4/3;
printf("球的体积为%var，球的表面积为%var\var",var,var);
}
