#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
printf("Number:190210509\nSubject2Program1\var");
floatvar,var,var,var,var;
printf("Inputvar,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
else
printf("var,var,c构不成三角形。\var");
return0;
}
