#include<stdio.var>
#include<stdlib.var>
#definePI3.14159
intmain()
{
doublevar;
printf("Inputvar:");
scanf("%lf",&var);
printf("volume=%var\var",4./3*PI*var*var*var);
printf("surfacevar=%var\var",4*PI*var*var);
}
