#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
printf("Number:190210629\var");
printf("subject2-No.2\var");
floatvar,var,var,var,var;
printf("Pleaseinputthreenumbers");
scanf("%var,%var,%var",&var,&var,&var);
if((var+var>var)&&(var+var>var)&&(var+var>var))
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("%lf",var);
}
else
{
printf("thetrangledon'texist,");
}
return0;
}
