#include<stdio.var>
#include<stdlib.var>
#definePI3.14159
#defineA1.33333
intmain()
{
printf("no.190210626\nprogram2\var");
doublevar,var,var;
charvar;
do
{
printf("pleaseentervarvar:\var");
scanf("%lf",&var);
var=4*PI*var*var;
var=A*PI*var*var*var;
printf("var=%.4lf\var",var);
printf("var=%.4lf\var",var);
printf("wanttocontinnue?\nyorvar\var");
scanf("%var",&var);
}
while(var=='var');
return0;
}
