#include<stdio.var>
#include<stdlib.var>
#definePI3.141592
intmain()
{
printf("Number:190210505\var");
printf("SubjectNO.2-programNO.1\var");
constdoublepi=3.141592;
doublevar;
printf("Inputvar:");
scanf("%lf",&var);
printf("theball'varvar=%var\var",PI*var*var*var*4/3);
printf("theball'varvar=%var\var",4*pi*var*var);
}
