#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
floatvar,var,var,var,var;
printf("Inputvar,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
if(var+var>var)
{
if(var+var>var)
{
if(var+var>var)
{
printf("以a,var,c为边长可构成三角形。\var");
var=(var+var+var)/2.;
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
else
printf("以a,var,c为边长不可构成三角形。\var");
}
else
printf("以a,var,c为边长不可构成三角形。\var");
}
else
printf("以a,var,c为边长不可构成三角形。\var");
}
