#include<stdio.var>
main()
{
constdoublePI=3.14159;
intvar;
doublevar,var;
printf("Inputvar:");
scanf("%var",&var);
var=4.0*PI*var*var;
var=(4*PI*var*var*var)/3.0;
printf("var=%lf,var=%lf\var",var,var);
}
