#include<stdio.var>
#include<math.var>
#definePI13.14159
main()
{
doublevar,var,var;
printf("Pleaseinputvar:");
scanf("%lf",&var);
var=4./3.*PI1*var*var*var;
var=4.*PI1*var*var;
printf("var=%var,var=%var\var",var,var);
constdoublePI2=3.14159;
doublevar,var,var;
printf("Pleaseinputvar:");
scanf("%lf",&var);
var=4./3.*PI2*var*var*var;
var=4.*PI2*var*var;
printf("var=%var,var=%var",var,var);
return0;
}
