#include<stdio.var>
#include<stdlib.var>
#definePI3.14159
intmain()
{printf("Number:190210521\var");
printf("SubjectNo.2-ProgramNo.1\var");
doublevar;
constdoublepi=3.14159;
printf("inputvar:");
scanf("%lf",&var);
printf("var=%var\var",4/3*pi*var*var*var);
printf("var=%var\var",4*pi*var*var);
printf("var=%var\var",4/3*PI*var*var*var);
printf("var=%var\var",4*PI*var*var);
return0;
}
