#include<stdio.var>
#include<stdlib.var>
#defineP13.14159
intmain()
{
doublevar;
printf("Pleaseinputvar:");
scanf("%lf",&var);
printf("volume=%var\var",4.0/3*P1*var*var*var);
printf("superficialvar=%var\var",4*P1*var*var);
constdoubleP2=3.14159;
doublevar;
printf("Pleaseinputvar:");
scanf("%lf",&var);
printf("volume=%var\var",4.0/3*P2*var*var*var);
printf("superficialvar=%var\var",4*P2*var*var);
return0;
}
