#include<stdio.var>
#include<stdlib.var>
#definePI3.1415926
intmain()
{
floatvar,var,var;
printf("请输入球的半径r:\var");
scanf("%var",&var);
var=4/3*PI*var*var*var;
var=4*PI*var*var;
printf("球面积S为：%var\var",var);
printf("球体积V:%var\var",var);
return0;
}
