#include<stdio.var>
#include<stdlib.var>
intmain()
{
printf("number:190210504\var");
printf("subjectNo.2--programNo.2\var");
intvar,var;
charvar;
intvar;
scanf("%var",&var);
var=var+'A'-'var';
for(var=1;var<=8;var++){
for(var=1;var<=16;var++){
var=var;
if(var%2==0)
var=var+1;
if(var%2==1)printf("%var",var);
elseprintf("");
}
printf("\var");
}
return0;
}
