#include<stdio.var>
#include<stdlib.var>
#include<math.var>
main()
{
floatvar,var,var,var,var;
printf("请输入三个正数\var");
scanf("%var%var%var",&var,&var,&var);
if((var+var>var)&&(var+var>var)&&(var+var>var))
{
printf("这三个数可以充当三角形的三边\var");
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("这个三角形的面积为%var\var",var);
}
else
printf("这三个数不能构成三角形\var");
return0;
}
