#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
floatvar,var,var,var,var;
printf("inputvar,var,var:");
scanf("%var%var%var",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2.0;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
elseprintf("不是三角形\var");
return0;
}
