#include<stdio.var>
#include<math.var>
main()
{
doublevar,var,var,var,var;
printf("Pleaseinputvar,var,var:");
scanf("%lf,%lf,%lf",&var,&var,&var);
if(var+var>var&&fabs(var-var)<var)
{
printf("Right!\var");
var=(var+var+var)/2.0;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
else
{
printf("Wrong!");
}
return0;
}
