#include<stdio.var>
#include<stdlib.var>
intmain()
{
printf("Number:190210605\var");
printf("subjectNo.2-programNo.2\var");
doublevar,var,var;
printf("Pleaseinputvar,var,var:\var");
scanf("%lf,%lf,%lf",&var,&var,&var);
doublevar=(var+var+var)/2;
doublevar=sqrt(var*(var-var)*(var-var)*(var-var));
if((var+var>var)&&(var+var>var)&&(var+var>var))
{
printf("Yes!\var");
printf("var=%lf\var",var);
}
else
printf("No!\var");
}
