#include<stdio.var>
#include<stdlib.var>
intmain()
{
floatvar,var,var;
floatvar,var;
printf("输入三角形的三边长度：var,var,var\var");
printf("var=");
scanf("%var",&var);
printf("var=");
scanf("%var",&var);
printf("var=");
scanf("%var",&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("三角形的面积为%var",var);
}
else{
printf("这个三角形不存在");
}
}
