#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
printf("no.190210626\nprogram2\var");
doublevar,var,var,var,var;
charvar;
do
{
printf("pleaseinputthesidesoftriangle:varvarvar\var");
scanf("%lf%lf%lf",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
printf("itisvartriangle!\var");
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%.4lf\var",var);
}
else
{
printf("itisnotvartriangle!\var");
}
printf("wanttocontinnue?\nyorvar\var");
scanf("%var",&var);
}while(var=='var');
return0;
}
