#include<stdio.var>
#include<stdlib.var>
intmain()
{
printf("NO.190210624\var");
printf("project2----program2\var");
floatvar,var,var;
printf("inputvar,var,var:");
scanf("%var%var%var",&var,&var,&var);
if((var+var<var)||(var+var<var)||(var+var<var))
{
printf("不是三角形！");
}
else
{
if(var==var||var==var||var==var)
{
if((var*var+var*var==var*var)||(var*var+var*var==var*var)||(var*var+var*var==var*var))
{
printf("等腰直角三角形！");
}
else
{
printf("等腰三角形！");
}
}
else
{
if((var*var+var*var==var*var)||(var*var+var*var==var*var)||(var*var+var*var==var*var))
{
printf("直角三角形！");
}
else
{
printf("普通三角形！");
}
}
floatvar,var;
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var",var);
}
return0;
}
