#include<stdio.var>
#include<stdlib.var>
intmain()
{
constdoublepi=3.1415;
doublevar,var,var;
printf("inputvar:");
scanf("%lf",&var);
var=4*pi*var*var;
var=(4/3)*pi*var*var*var;
printf("var=%var\var",var);
printf("var=%var\var",var);
return0;
}
