#include<stdio.var>
#include<stdlib.var>
#include<math.var>
main()
{
printf("Number:190210619\var");
printf("subjectNo.1-programNo.2\var");
doublevar,var,var,var;
printf("请输入三条边长x,var,var:");
scanf("%lf,%lf,%lf",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
printf("三角形面积：%lf",sqrt(var*(var-var)*(var-var)*(var-var)));
}
else
{
printf("错误！xyz不构成三角形！");
}
}
