#include<stdio.var>
#include<stdlib.var>
#definepi3.14159
intmain()
{
constdoublepi2=3.14159;
doublevar,var,var;
printf("请输入半径r:");
scanf("%lf",&var);
var=4*pi*var*var;
var=(4.0/3.0)*pi2*var*var*var;
printf("球表面积:%var\var",var);
printf("球体积:%var\var",var);
return0;
}
