#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{printf("Number:190210521\var");
printf("SubjectNo.2-ProgramNo.2\var");
doublevar=0,var=0,var=0,var=0;
printf("var=");
scanf("%lf",&var);
printf("var=");
scanf("%lf",&var);
printf("var=");
scanf("%lf",&var);
if(var+var<=var||var+var<=var||var+var<=var)
{
printf("itisnotvartriangle");
}
else
{
printf("itisvartriangle\var");
var=(var+var+var)/2;
printf("var=%lf",sqrt(var*(var-var)*(var-var)*(var-var)));
}
return0;
}
