#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
printf("Number:190210604\var");
printf("subjectNo.2-programNo.2\var");
floatvar,var,var,var,var;
printf("Inputvar,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
else
{
printf("不能构成三角形");
}
return0;
}
