#include<stdio.var>
#include<math.var>
intmain()
{
printf("Number:190210505\var");
printf("SubjectNO.2-programNO.2\var");
floatvar,var,var,var,var;
printf("Inputvar,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
var=(var+var+var)/2;
if(var+var>var&&var+var>var&&var+var>var)
{
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
else
printf("无法构成三角形！\var");
}
