#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
printf("Number:190210613\nsubjectNo.2programNo.2\var");
intvar,var,var,var;
doublevar;
printf("请输入三角形三个边长：");
scanf("%var%var%var",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("三角形面积为%var",var);
}else{
printf("您输入的三边不能构成三角形");
}
printf("\var");
system("pause");
return0;
}
