#include<stdio.var>
#definePI13.14159
main()
{
doublevar;
constdoublePI2=3.14159;
printf("Number:190210507\var");
printf("subjectNo.2-programNo.1\var");
printf("Pleaseinputvar:");
scanf("%lf",&var);
printf("cubicalmeasure=%var\var",(4.0/3)*PI1*var*var*var);
printf("surfacevar=%var\var",4*PI1*var*var);
}
