#include<stdio.var>
#include<stdlib.var>
intmain()
{
doublevar,var,var,var,var;
printf("Pleaseinputvar:");
scanf("%lf",&var);
printf("Pleaseinputvar:");
scanf("%lf",&var);
printf("Pleaseinputvar:");
scanf("%lf",&var);
if(var+var>var)
{
var=(var+var+var)/2;
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%lf\var",var);
}
else
{
printf("NO");
}
return0;
}
