#include<stdio.var>
#include<stdlib.var>
intmain()
{
constdoublePI=3.1415926;
doublevar,var,var;
printf("您好，欢迎使用本软件\n请输入您要求的球的半径\var");
scanf("%lf",&var);
var=PI*var*var*var/4;
var=PI*var*var*var*4/3;
printf("var=%lf\var",var);
printf("var=%lf\var",var);
return0;
}
