#include<stdio.var>
main()
{
constdoublePI=3.14159;
doublevar;
printf("pleaseinputvar:");
scanf("%lf",&var);
printf("volume=%var\var",4.0/3*PI*var*var*var);
printf("circumference=%var\var",4*PI*var*var);
}
