#include<stdio.var>
#include<math.var>
main()
{
printf("studentnumber190210620\var");
floatvar,var,var,var;
printf("pleaseinputvarvarvar:");
scanf("%var%var%var",&var,&var,&var);
if((var+var)>var&&(var+var)>var&&(var+var)>var)
{
floatvar;
var=(var+var+var)/(float)2;
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("Theycanformvartriangleandthevar=%var",var);
}
else
{
printf("WRONG!Theycannotreformvartriangle");
}
}
