#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
floatvar,var,var,var;
floatvar;
printf("pleaseinputthreesidesoftriangle:");
scanf("%var,%var,%var",&var,&var,&var);
if((var+var)>var&&(var+var)>var&&(var+var)>var)
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
}
else
{printf("triangleisnotexist!\var");
}
printf("thevarofthetriangleis:%var\var",var);
}
