#include<stdio.var>
#include<stdlib.var>
#definePI3.141592
intmain()
{
doublevar;
printf("Inputvar:");
scanf("%lf",&var);
printf("var=%var\var",4*PI*var*var);
printf("var=%var\var",(4*PI*var*var*var)/3);
return(0);
}
