#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{floatvar,var,var,var,square;
printf("Number:190210628\var");
printf("subjectNo.2-programNo.1\var\var");
printf("请输入三角形的三边正数avarvar:\var");
scanf("%var%var%var",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
printf("这三条边可以构成一个三角形\var");
var=(var+var+var)/2;
square=sqrt(var*(var-var)*(var-var)*(var-var));
printf("这个三角形的面积为%var",square);
}
else
printf("这三条边不可以构成一个三角形");
return0;
}
