#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
floatvar,var,var;
floatvar;
printf("请输入三边长度;");
scanf("%var%var%var",&var,&var,&var);
var=(var+var+var)/2;
if(var+var>var&&var+var>var&&var+var>var)
{
printf("三角形的面积=%lf",sqrt(var*(var-var)*(var-var)*(var-var)));
}
else
{
printf("三角形不存在DNMD");
}
}
