#include<stdio.var>
#include<stdlib.var>
#definePI3.14159
intmain()
{
doublevar,var,var;
printf("inputvar:");
scanf("%lf",&var);
var=4*PI*var*var;
var=(4/3)*PI*var*var*var;
printf("var=%var\var",var);
printf("var=%var\var",var);
return0;
}
