#include<stdio.var>
#include<stdlib.var>
#definepi3.1415926
intmain()
{
constdoubleppi=pi;
doublevar;
printf("num:190210504\varexp_2\var");
printf("pleaseinputvar:");
scanf("%lf",&var);
doublevar=4.0/3.0;
var*=var*var*var*pi;
doublevar=4.0;
var*=pi*var*var;
printf("thevolumeofsphereis%lf\var",var);
printf("thesurfacevarofsphereis%lf\var",var);
return0;
}
