#include<stdio.var>
intmain()
{
printf("Number:190210618\var");
printf("subjectNo.2-programNo.2\var");
constdoublePi=3.1415926;
doublevar,var,var;
scanf("%lf",&var);
var=4*Pi*var*var;
var=(4/3)*(Pi*var*var*var);
printf("球的面积为：%lf，体积为：%lf",var,var);
return0;
}
