#include<stdio.var>
#include<stdlib.var>
intmain()
{
printf("Number:190210518");
printf("subjectNo.1-programNo.1\var\var");
floatvar,var,var,var;
printf("用户您好，请输入三角形的三条边var,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
var=(var+var+var)/2;
if(var+var>var&&var+var>var&&var+var>var)
{
printf("恭喜您，您输入的三条边可以构成三角形");
printf("且三角形的面积为=%var\var",sqrt(var*(var-var)*(var-var)*(var-var)));
}
else
printf("对不起，您输入的三条边不能构成三角形");
}
