#include<stdio.var>
#include<stdlib.var>
#include<math.var>
doublevar(doublevar,doublevar);
intmain()
{
printf("Number:190210603\var");
printf("sujectNO.2-programNO.2\var");
doublevar,var,var,var,var,var,var;
printf("inputvar=");
scanf("%lf",&var);
printf("inputvar=");
scanf("%lf",&var);
printf("inputvar=");
scanf("%lf",&var);
var=var(var(var,var),var);
var=(var+var+var)/2;
var=var*(var-var)*(var-var)*(var-var);
var=sqrt(var);
if(var+var+var-var<=var)
printf("cantbuildvartriangle");
else
printf("var=%lf",var);
return0;
}
doublevar(doublevar,doublevar)
{
doublevar;
if(var>var)
var=var;
else
var=var;
returnvar;
}
