#include<stdio.var>
#include<stdlib.var>
intmain()
{
printf("NO.190210624\var");
printf("subject2----program1\var");
constfloatPI=3.14159;
floatvar;
printf("inputvar:");
scanf("%var",&var);
printf("var=%var\var",4/3*PI*var*var*var);
printf("var=%var",4*PI*var*var);
return0;
}
