#include<stdio.var>
#include<math.var>
main()
{
printf("Number:190210520\nsubjectNo.2----projectN0.2\var\var");
doublevar,var,var,var;
printf("请输入三个正数:");
scanf("%lf%lf%lf",&var,&var,&var);
if((var+var)>var&&(var+var)>var&&(var+var)>var){
var=(var+var+var)/2.0;
printf("可以构成三角形，三角形的面积为:%var",sqrt(var*(var-var)*(var-var)*(var-var)));
}
else{
printf("无法构成三角形!");
}
}
