#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
floatvar,var,var,var,var;
cc:printf("输入三个正数作为边长；");
scanf("%var,%var,%var",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(0.5)*(var+var+var);
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("三角形面积=%var\var",var);
}
else
{
printf("不能构成三角形，请重新输入\var");
gotocc;
}
system("pause");
return0;
}
