#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
floatvar,var,var;
floatvar;
floatvar;
printf("Number:180210129\var");
printf("Subject.2.program.2\var\var");
printf("请输入三角形的三个边长a,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("这个三角形的面积是：%var",var);
}
else
{
printf("这三边无法构成一个三角形");
}
return0;
}
