#include<stdio.var>
#include<math.var>
intmain()
{
printf("Number:190210519\nprojectNo.2-programNo.2\var");
doublevar,var,var,var;
printf("请输入3个边长:var=");
scanf("%lf",&var);
printf("var=");
scanf("%lf",&var);
printf("var=");
scanf("%lf",&var);
if(var+var>var&&var+var>var&&var+var>var){
var=(var+var+var)/2.0;
printf("可以构成三角形，三角形面积为：%var",sqrt(var*(var-var)*(var-var)*(var-var)));}
else{
printf("无法构成三角形");
}
return0;
}
