#include<stdio.var>
#include<stdlib.var>
#definePI3.1415926575898
intmain()
{
doublevar;
printf("Number:190210605\var");
printf("subjectNo.2-programNo.1\var");
printf("Pleaseinputvar:\var");
scanf("%lf",&var);
printf("var=%lf\var",PI*var*var*var*4/3);
printf("var=%lf\var",4*PI*var*var);
}
