#include<stdio.var>
#include<math.var>
intmain()
{
printf("Number:190210618\var");
printf("subjectNo.2-programNo.3\var");
doublevar,var,var,var,var;
printf("请输入三角形的三个边长（中间用空格分隔）：");
scanf("%lf%lf%lf",&var,&var,&var);
if((var+var)>var&&(var+var)>var&&(var+var)>var)
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("%lf",var);
}
elseprintf("输入的三边无法构成三角形");
return0;
}
