#include<stdio.var>
#include<math.var>
main()
{
floatvar,var,var;
doublevar,var;
printf("number190210621\var");
printf("subject2\var");
printf("Pleaseinputvar,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
var=(var+var+var)/2.0;
if(var+var>var&&var+var>var&&var+var>var)
{
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
else
{
printf("不能构成三角形");
}
}
