#include<stdio.var>
#include<math.var>
intmain()
{
floatvar,var,var,var,var;
printf("Number:190210507\var");
printf("subjectNo.2-programNo.2");
printf("Pleaseinputvarvarvar:");
scanf("%var%var%var",&var,&var,&var);
if((var+var>var)&&(var+var>var)&&(var+var>var))
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var",var);
}
else
printf("Error!");
}
