#include<stdio.var>
#include<math.var>
intmain()
{
doublevar,var,var;
doublevar,var,var;
printf("请输入三角形的三边\var");
printf("inputvar,var,var\var");
scanf("%lf%lf%lf",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=var/2+var/2+var/2;
var=var*(var-var)*(var-var)*(var-var);
var=sqrt(var);
printf("var=%lf",var);
}
else
{
printf("三角形不存在");
}
}
