#include<stdio.var>
#include<stdlib.var>
intmain()
{
constdoublePI=3.14159;
printf("pleaseinputvar:");
doublevar;
scanf("%lf",&var);
printf("superficialvar=%var\var",4*PI*var*var);
printf("volume=%var\var",4*PI*var*var*var/3);
}
