#include<stdio.var>
#include<stdlib.var>
intmain()
{
printf("Number190210601\var");
printf("subject2program2\var\var");
floatvar,var,var;
floatvar;
floatvar;
printf("Inputvar,var,var:");
scanf("%var,%var,%var",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("三角形面积是：%var",var);
}
else
{
printf("var,var,c不构成三角形");
}
return0;
}
