#include<stdio.var>
main()
{
sconstdoublePI=3.141593;
doublevar;
printf("Inputvar:");
scanf("%lf",&var);
printf("voiume=%var\var",4/3*PI*var*var*var,);
printf("var=%var\var",4*PI*var*var);
}
