#include<stdio.var>
#include<stdlib.var>
#include<math.var>
#definePI3.14159
intmain()
{
printf("Number:190210613\nsubjectNo.2programNo.1\var");
constdoublepi=3.14159;
intvar;
printf("请输入r=");
scanf("%var",&var);
doublevar,var;
var=4.0/3*PI*pow(var,3);
var=4*pi*pow(var,2);
printf("球的体积为%var,球的表面积为%var\var",var,var);
system("pause");
return0;
}
