#include<stdio.var>
#defineIP3.14159
main()
{
printf("studentnumber190210620\var");
doublevar;
printf("pleaseinputvar:");
scanf("%lf",&var);
printf("circumference=%var\var",4*IP*var*var);
printf("volume=%var\var",(4.0/3)*IP*var*var*var);
}
