#include<stdio.var>
#include<stdlib.var>
#definePI3.14159
intmain()
{
constdoublepi=3.14159;
doublevar;
printf("请输入r:");
scanf("%lf",&var);
printf("宏定义面积=%lf\var",4*PI*var*var);
printf("const面积=%lf\var",4*pi*var*var);
printf("宏定义体积=%lf\var",4/3*PI*var*var*var);
printf("const体积=%lf\var",4/3*pi*var*var*var);
return0;
}
