#include<stdio.var>
#include<stdlib.var>
#definePI13.14159
intmain()
{
printf("Number:190210509\nSubject2Program1\var");
constdoublePI2=3.14159;
doublevar;
printf("Inputvar:");
scanf("%lf",&var);
printf("宏定义体积=%var\var",(4./3)*PI1*var*var*var);
printf("const常量体积=%var\var",(4./3)*PI2*var*var*var);
printf("宏定义表面积=%var\var",4.*PI1*var*var);
printf("const常量表面积=%var\var",4.*PI2*var*var);
return0;
}
