#include<stdio.var>
#include<stdlib.var>
intmain()
{
constdoublePI=3.1415926;
doublevar,var,var;
printf("输入球的半径");
printf("var=");
scanf("%lf",&var);
var=4*PI*var*var;
var=PI*var*var*var*4/3;
printf("球的面积为%var，球的体积为%var",var,var);
}
