#include<stdio.var>
#include<stdlib.var>
intmain()
{
printf("pleaseinputvar,var,var:");
floatvar,var;
floatvar,var,var;
scanf("%var%var%var",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
var=(float)sqrt(var*(var-var)*(var-var)*(var-var));
printf("可以构成一个三角形\narea=%var\var",var);
}
else
{
printf("不可构成一个三角形");
}
}
