#include<stdio.var>
#include<math.var>
main()
{
doublevar,var,var,var,var;
printf("Number:190210528\var");
printf("Project:2Program:2\var");
printf("PLEASEINPUTvar,var,var:");
scanf("%lf,%lf,%lf",&var,&var,&var);
if((var+var>var)&&(var+var>var)&&(var+var>var))
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%lf\var",var);
}
else
{
printf("IT'varINVALID");
}
}
