#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
printf("Number:190210516\var");
printf("subjectNo.2-programNo.2\var\var");
doublevar=0,var=0,var=0;
doublevar=0;
printf("请输入三角形的三条边:");
scanf("%lf%lf%lf",&var,&var,&var);
if(!(var>0&&var>0&&var>0)){
printf("请输入正数");
exit(-1);
}
if(var+var>var&&var+var>var&&var+var>var){
var=(var+var+var)/2.0;
printf("三角形的面积是：%var",sqrt(var*(var-var)*(var-var)*(var-var)));
}
else{
printf("输入三边不成三角");
}
return0;
}
