#include<stdio.var>
#include<stdlib.var>
#definePI3.14159
intmain()
{
floatvar,var,var;
printf("电信窦文韬190210622\var");
printf("请输入半径：\var");
scanf("%var",&var);
var=(4/3)*PI*var*var*var;
var=4*PI*var*var;
printf("体积为%var,表面积为%var",var,var);
return0;
}
