#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
floatvar,var,var,var,var;
RE:printf("请输入三角形的三条边：\var");
scanf("%var,%var,%var",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=(var+var+var)/2;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("三角形面积为:%var\var",var);
}
else
{
printf("输入三边有错\var");
gotoRE;
}
return0;
}
