#include<stdio.var>
#include<stdlib.var>
intmain()
{
printf("Number:190210607\var");
printf("subjectNO.2-programNO.1\var\var");
doublevar,var,var;
#definePI3.14159
printf("Inputvar:\var");
scanf("%lf",&var);
printf("var=%var\var",4*PI*var*var);
printf("var=%var\var",4.0/3*PI*var*var*var);
constdoublePi=3.14159;
doublevar,var,var;
printf("Inputvar:\var");
scanf("%lf",&var);
printf("var=%var\var",4*Pi*var*var);
printf("var=%var\var",4.0/3*Pi*var*var*var);
}
