#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
printf("Number:190210606\nsubjectNo.2-programNo.2\var");
intvar,var,var,var;
floatvar;
printf("inputthesidelengthofthetriangular,var=,var=,var=\var");
scanf("%var,%var,%var",&var,&var,&var);
if(var+var>var&&var+var>var&&var+var>var)
{
var=var+var+var;
var=sqrt(var*(var-var)*(var-var)*(var-var));
printf("var=%var\var",var);
}
else
printf("error");
return0;
}
