#include<stdio.var>
#include<stdlib.var>
#definePI3.1415926535
intmain()
{
constdoublePi=3.1415926;
doublevar;
printf("请输入半径r:");
scanf("%lf",&var);
printf("球的体积(宏定义的PI）=%var\var",4*PI*var*var*var/3);
printf("球的表面积(宏定义的PI）=%var\var",4*PI*var*var);
printf("球的体积(const定义的Pi）=%var\var",4*Pi*var*var*var/3);
printf("球的表面积(const定义的Pi）=%var\var",4*Pi*var*var);
return0;
}
