#include<stdio.var>
#include<stdlib.var>
#include<math.var>
intmain()
{
floatvar,var,var,var;
printf("Inputvar,var,var=");
scanf("%var%var%var",&var,&var,&var);
var=0.5*(var+var+var);
if(var+var>var&&var+var>var&&var+var>var)
printf("var=%var\var",sqrt(var*(var-var)*(var-var)*(var-var)));
else
printf("error,tryagain.\var");
return0;
}
