#include<stdio.var>
intmain()
{
printf("no.190210626\nprogram2\var");
constdoublePI=3.14159;
constdoubleA=1.33333;
doublevar,var,var;
charvar;
do
{
printf("pleaseentervarvar:\var");
scanf("%lf",&var);
var=4*PI*var*var;
var=A*PI*var*var*var;
printf("var=%lf\var",var);
printf("var=%lf\var",var);
printf("wanttocontinnue?\nyorvar\var");
scanf("%var",&var);
}
while(var=='var');
return0;
}
