#include<stdio.var>
#include<stdlib.var>
intmain()
{
constdoublePI=3.141592;
doublevar;
printf("Inputvar:");
scanf("%lf",&var);
printf("var=%var\var",4*PI*var*var);
printf("var=%var\var",(4*PI*var*var*var)/3);
return(0);
}
