#include<stdio.var>
#include<stdlib.var>
intmain()
{
constdoublepi=3.1415;
floatvar,var,var;
printf("输入半径:");
scanf("%var",&var);
var=var*var*var*pi*4/3;
var=4*pi*var*var;
printf("球的体积=%var\var",var);
printf("球的表面积=%var\n4",var);
system("pause");
return0;
}
