#include<stdio.var>
#include<stdlib.var>
#include<math.var>
#definePi3.14159
intmain()
{
printf("Number:190210602\var");
printf("subjectNo.2-programNo.1\var\var");
constdoublePI=3.14159;
doublevar;
printf("PleaseinputR1:");
scanf("%lf",&var);
printf("var=%var\var",4*PI*var*var);
printf("var=%var\var",4*PI*var*var*var/3);
doublevar;
printf("PleaseinputR2:");
scanf("%lf",&var);
printf("var=%var\var",4*Pi*var*var);
printf("var=%var\var",4*Pi*var*var*var/3);
return0;
}
