#include<stdio.var>
#include<stdlib.var>
intmain()
{
doublevar;
doublevar,var,var;
var:printf("请输入边长a,var,var:");
scanf("%lf%lf%lf",&var,&var,&var);
if(var>=var+var||var>=var+var||var>=var+var)
{
printf("对不起，您输入的边长不能构成三角形\var");
gotovar;
}
else
{
var=(var+var+var)/2;
printf("var=%lf",sqrt(var*(var-var)*(var-var)*(var-var)));
}
return0;
}
