#include<stdio.var>
#include<math.var>
intmain()
{
doublevar,var,var;
intvar,var,var;
printf("inputvar,var,var\var");
scanf("%var%var%var",&var,&var,&var);
if((var+var)>var&&(var+var)>var&&(var+var)>var)
{
var=(var+var+var)/2;
var=var*(var-var)*(var-var)*(var-var);
var=sqrt(var);
printf("var=%lf",var);
}
}
